### PR TITLE
Better Colored and Capitalized Usernames.

### PR DESCRIPTION
**Pull request by ThatGravyBoat**

### CODE REVIEW

**Comment by mini-bomba** [comment]
Thanks for the pull request! I'll test & merge it whenever I have time (which is not now)

Btw, here's a GitHub protip: include something like "This closes #\<issue\>" in your pull request's description to automatically link your pull request to an issue. In this case, you'd write "This fixes #14".

**Comment by ThatGravyBoat** [comment]
I did realize there was an issue for it until after I made the PR, ill remember to use the auto-closing syntax in PR message for next time.

**Comment by mini-bomba** [comment]
> I did realize there was an issue for it until after I made the PR, ill remember to use the auto-closing syntax in PR message for next time.

You can always edit the description

**Comment by mini-bomba** [comment]
Seems to produce more accurate colors, but looks like some colors are not able to resolve and result in a white nick color.
It's still better than the current implementation, so I'll merge it

**Comment by domiehomie** [comment]
> Seems to produce more accurate colors, but looks like some colors are not able to resolve and result in a white nick color. It's still better than the current implementation, so I'll merge it

from what ive gathered, sometimes the color will just return null, so I'm guessing thats the issue here as well.

**Comment by mini-bomba** [comment]
> > Seems to produce more accurate colors, but looks like some colors are not able to resolve and result in a white nick color. It's still better than the current implementation, so I'll merge it
> 
> from what ive gathered, sometimes the color will just return null, so I'm guessing thats the issue here as well.

I think that's the issue here. I was thinking if maybe randomly choosing a fallback color for each user (and caching it, so they always get the same fallback color, at least until the game is closed) would be better than just displaying it as white... Though that would make those users have a different color than on stream.

**Comment by domiehomie** [comment]
> > > Seems to produce more accurate colors, but looks like some colors are not able to resolve and result in a white nick color. It's still better than the current implementation, so I'll merge it
> > 
> > from what ive gathered, sometimes the color will just return null, so I'm guessing thats the issue here as well.
> 
> I think that's the issue here. I was thinking if maybe randomly choosing a fallback color for each user (and caching it, so they always get the same fallback color, at least until the game is closed) would be better than just displaying it as white... Though that would make those users have a different color than on stream.

might be something to shoot an issue to twitch4j or the twitch API team for

**Comment by mini-bomba** [comment]
> might be something to shoot an issue to twitch4j or the twitch API team for

I think it's null if the user has not specified the color themselves, so it is using the default one... maybe the T4J devs know a little more about how to get that default color for a user

**Comment by ThatGravyBoat** [comment]
so with a tiny bit of digging in the website js how it works is like this, this is some JS but I commented it to explain it a bit but it's essentially random.
This is not a direct copy of the code on their site because it's minified so I changed it to a more readable format.
```js
const colors = [
    "#FF0000",
    "#0000FF",
    "#008000",
    "#B22222",
    "#FF7F50",
    "#9ACD32",
    "#FF4500",
    "#2E8B57",
    "#DAA520",
    "#D2691E",
    "#5F9EA0",
    "#1E90FF",
    "#FF69B4",
    "#8A2BE2",
    "#00FF7F"
]

var colorCache = {}

function getOrSetRandomColor(userId, value) {
    //Lines in the return
    //Line 1: if (value === void 0) then true so it will set the value to 15, 
    // but from checking the code in the main js file they dont ever pass in value so it will always set value to 15
    //Line 2: this is to check the cache. if value in cache is a number then it will be false and wont go to the second statement
    // therefore it wont set the color.
    //line 3: it will then pull an index from the cache and then pull that color from the color list.
    return (
      void 0 === value && (value = 15), 
      "number" != typeof colorCache[userId] && (colorCache[userId] = Math.floor(Math.random() * value)), 
      colors[colorCache[userId]]
    );
}
````

**Comment by ThatGravyBoat** [comment]
I can make another PR to also implement this if the color is null

**Comment by mini-bomba** [comment]
So it's just a random color from a list then? ngl, I expected them to generate it based on the user's ID or something, but if this just random, then it's fair to simply choose a random color `EnumChatFormatting` as a fallback color. This should be fairly simple to implement. *Just make sure not to include a non-color formatting in the choices*

**Pull request merged**
